### PR TITLE
Implemented Card.cs Pack.cs Testing.cs

### PR DESCRIPTION
**Pull request by MuchMarts**

### CODE REVIEW

**Comment by Katie-Maddick** [comment]
Overall this was really good. Your code was all well commented so that it was clear what each method did. Your error handling worked correctly and was used effectively. Your extra methods also added good functionality to the program. 
All that could be done to improve would be that when you deal a card or multiple cards, it always deals random cards even when you haven't shuffled them yet just to prevent confusion. You can either do this by making it so the card chosen is random by using the random method, or by having it so the cards are shuffled initially after they have been created.

**Comment by MuchMarts** [comment]
> 

I see your point with dealing random cards even if the pack has not been shuffled but my idea was that in real life if you had an unshuffled deck you would deal cards sequentially I.E. one after another thus of you want them in a random order you should shuffle the cards first. 
Do you think that the pack of cards should be shuffled no matter what when dealing? I.e. even if its initialized and unshuffled they should be automatically shuffled.

**Comment by BeansAreOk** [comment]
The clear comments made on the code, the functionality provided by the program as well as the amount of different options provided in the test in summary makes this a very good piece of work which even exceeds what was asked for by the assignment. However, I still believe that the error handling whilst dealing multiple cards should be amended, as inputting more than 52 cards still prints the 52, with no message provided to the user that they are going above the limit. Also although this is only purely a design choice and is trivial in the testing stages of the code, it would still help to provide more accessibility to a user if names were given to the suits as opposed to numbers so they're easier to read. Therefore, the program itself functions very well it just needs some slight accessibility changes to improve it even more.

**Comment by MuchMarts** [comment]
As per your suggestion Added translation from Suit int value to a String name so its easier to read. 
Also changed how errors are handled when dealing multiple cards, initially it was designed in a way where it would try to deal as many cards as possible but now I see that it was not intuitive and was not clear to the user why that happened.

**Comment by smoothbrain420** [comment]
Its impressive how well all the code is divided. Made everything very easy to read and follow. Documentation is very clear and well done. Pretty much a comment after every single function even expanding on the inheritance between classes and why you used it. Error handling is flawless having case sensitive checks for every possible input and handling miss inputs accordingly. The functionality of the program goes far beyond the brief with many extra methods regarding the testing methods. its exceptional in almost every metric. I honestly don't how I could improve the code without repeating previous code reviews.

**Comment by Lyorial** [comment]
The code is divided very well, which allowed for the code to be presentable and therefore easy to understand and read along, this worked in tandum with the comments to make the code a pleasure to read. There is a lot of error handling and the program meets all the criteria for the brief. Without repeating previous code reviews, theres not much to add in to what can improve this program. Very well done Martins!

**Pull request merged**
